import { ATTRIBUTE_EXAMPLES } from '../../attributes/dto/attribute.examples.js';

export const PRODUCT_ATTRIBUTE_EXAMPLES = {
  attributeId: '550e8400-e29b-41d4-a716-446655440030',
  productId: '550e8400-e29b-41d4-a716-446655440000',
  variantValueId: '550e8400-e29b-41d4-a716-446655440040',
  productAttributeVariantId: '550e8400-e29b-41d4-a716-446655440050',
  createdAt: '2026-09-02T10:00:00.000Z',
} as const;

export const PRODUCT_ATTRIBUTE_RESPONSE_EXAMPLE = {
  id: PRODUCT_ATTRIBUTE_EXAMPLES.attributeId,
  productId: PRODUCT_ATTRIBUTE_EXAMPLES.productId,
  attributeValueIds: [PRODUCT_ATTRIBUTE_EXAMPLES.variantValueId],
};
export const CREATE_PRODUCT_ATTRIBUTE_EXAMPLE = {
  productId: PRODUCT_ATTRIBUTE_EXAMPLES.productId,
  attributeValueIds: [PRODUCT_ATTRIBUTE_EXAMPLES.variantValueId],
};

export const CREATE_PRODUCT_ATTRIBUTE_VARIANT_EXAMPLE = {
  attributeId: PRODUCT_ATTRIBUTE_EXAMPLES.attributeId,
  variantValueId: ATTRIBUTE_EXAMPLES.variantValueId,
};

/** @deprecated use PRODUCT_ATTRIBUTE_EXAMPLES */
export const VARIANT_EXAMPLES = PRODUCT_ATTRIBUTE_EXAMPLES;
/** @deprecated use PRODUCT_ATTRIBUTE_RESPONSE_EXAMPLE */
export const PRODUCT_VARIANT_RESPONSE_EXAMPLE =
  PRODUCT_ATTRIBUTE_RESPONSE_EXAMPLE;
/** @deprecated use CREATE_PRODUCT_ATTRIBUTE_EXAMPLE */
export const CREATE_PRODUCT_VARIANT_EXAMPLE = CREATE_PRODUCT_ATTRIBUTE_EXAMPLE;
/** @deprecated use CREATE_PRODUCT_ATTRIBUTE_VARIANT_EXAMPLE */
export const CREATE_PRODUCT_VARIANT_ATTRIBUTE_EXAMPLE =
  CREATE_PRODUCT_ATTRIBUTE_VARIANT_EXAMPLE;
